import { Component } from '@angular/core';
import { IonicPage, NavController, NavParams, } from 'ionic-angular';
import { ViewController } from 'ionic-angular';



/**
 * Generated class for the InformacionPage page.
 *
 * See https://ionicframework.com/docs/components/#navigation for more info on
 * Ionic pages and navigation.
 */

@IonicPage()
@Component({
  selector: 'page-informacion',
  templateUrl: 'informacion.html',
})
export class InformacionPage {

  character;
  pages: Array<{title: string, component: any, icon: string}>;

  constructor(
  	public navCtrl: NavController, 
  	public navParams: NavParams,
    public viewCtrl: ViewController,
    public params: NavParams,
  	) {
    var characters = [
      {
        name: 'Press banco Plano',
        quote1: '1.Acostarse en un banco plano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/press banco plano.gif', 
        photo: 'assets/imagenes/pectorales/press banco plano.jpg' ,                /*0*/
       
      },                                                          
      {/*1*/
        name: 'Press banco manos juntas',
        quote1: '1.Acostarse en un banco plano' ,
        quote2: '2.Tomar barra en agarre estrecho' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/press banco manos juntas.gif', 
        photo: 'assets/imagenes/pectorales/press banco manos juntas.jpg' , 
      },
      {/*2*/
        name: 'Press  banco inclinado',
        quote1: '1.Acostarse en un banco inclinado' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/press banco inclinado.gif', 
        photo: 'assets/imagenes/pectorales/press banco inclinado.jpg' ,
      },
      {/*3*/
        name: ' Press banco declinado  ',
        quote1: '1.Acostarse en un banco decliado' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/press banco declinado.gif', 
        photo: 'assets/imagenes/pectorales/press banco declinado.jpg' ,
      },
      {/*4*/
        name: 'Press de barra en maquina',
        quote1: '1.Sentarse con la espalda recta' ,
        quote2: '2.Tomar las barras de los mandos' ,
        quote3: '3.Estira tus brazos mientras exhalas' ,
        quote4: '4.Inhala mientras recoges los brazos' ,
        image: 'assets/imagenes/pectorales/press de barra en maquina.gif', 
        photo: 'assets/imagenes/pectorales/press de barra en maquina.jpg' ,
      },
      {/*5*/
        name: 'Press  con mancuernas',
        quote1: '1.Acostarse en un banco plano' ,
        quote2: '2.Tomar dos mancuernas del mismo peso' ,
        quote3: '3.Exhalar mientras estiras los brazos' ,
        quote4: '4.Inhalar mientras bajas las mancuernas' ,
        quote5: '5.Repetir el movimiento ritmicamente' ,
        image: 'assets/imagenes/pectorales/press  con mancuernas.gif', 
        photo: 'assets/imagenes/pectorales/press  con mancuernas.jpg' ,
      },
      {/*6*/
        name: ' Pull over con mancuerna',
        quote1: '1.Acostarse en un banco plano' ,
        quote2: '2.Tomar la barra en pronacion ' ,
        quote3: '3.Tomar barra al hancho de los hombros' ,
        quote4: '4.Bajar la barra por detras de la cabeza' ,
        quote5: '5.Exhalar volviendo a la posicion inicial',
        image: 'assets/imagenes/pectorales/pull over con mancuerna.gif', 
        photo: 'assets/imagenes/pectorales/pull over con mancuerna.jpg' ,
      },
      {/*7*/
        name: 'Apertura de contractor',
        quote1: '1.Sentarse en la maquina con espalda recta' ,
        quote2: '2.Apoyar los brazos en la maquina' ,
        quote3: '3.Cerrar los brazos ' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/apertura de contractor.gif', 
        photo: 'assets/imagenes/pectorales/apertura de contractor.jpg' ,
      },
      {/*8*/
        name: 'Cruce de poleas',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/cruce de poleas.gif', 
        photo: 'assets/imagenes/pectorales/cruce de poleas.jpg' ,
      },/*////////////////////////////////////////////////////////////////////////////////////////////*/
      {/*9*/
        name: 'Flexiones de brazos',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/flexiones de brazos.gif', 
        photo: 'assets/imagenes/pectorales/flexiones de brazos.jpg' ,
      },
      {/*10*/
        name: 'Flexion de triceps',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/flexion de triceps.gif', 
        photo: 'assets/imagenes/pectorales/flexiones de brazos.jpg' ,
      },
      { /*11*/
        name: 'Flexion diamante',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/Flexion diamante.gif', 
        photo: 'assets/imagenes/pectorales/flexiones de brazos.jpg' ,
      },
      {/*12*/
        name: 'Flexion  inclinado',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/flexion  inclinado.gif', 
        photo: 'assets/imagenes/pectorales/flexion  inclinado.png' ,
      },
      { /*13*/
        name: 'Flexiones declinadas',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/flexion declinada.jpeg', 
        photo: 'assets/imagenes/pectorales/flexion declinada.png' ,
      },
      { /*14*/
        name: 'Fondos',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/fondos.gif', 
        photo: 'assets/imagenes/pectorales/fondos.jpg' ,
      },
      {/*15*/
        name: 'Flexion con palmadas',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/flexion con palmadas.gif', 
        photo: 'assets/imagenes/pectorales/flexiones de brazos.jpg' ,
      },
      {/*16*/
        name: 'Flexion delfin',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/flexion delfin.gif', 
        photo: 'assets/imagenes/pectorales/flexiones de brazos.jpg' ,
        
      },
      {/*17*/
        name: 'Flexion arquero',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/Flexion arquero.gif', 
        photo: 'assets/imagenes/pectorales/flexiones de brazos.jpg' ,
      },/*///////////////////////////////////////////////////////////////////////////////////////////////////////////*/
      {/*18*/
        name: 'Curl de biceps alterno',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/biceps/Curl de Biceps alterno.gif', 
        photo: 'assets/imagenes/biceps/Curl de Biceps alterno.jpg' ,
      },
      { /*19*/
        name: 'Curl de biceps concentrado',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/biceps/Curl de biceps concentrado.gif', 
        photo: 'assets/imagenes/biceps/Curl de biceps concentrado.jpg' ,
      },
      {/*20*/
        name: 'Curl martillo alterno',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/biceps/Curl martillo alterno.gif', 
        photo: 'assets/imagenes/biceps/Curl martillo alterno.jpg' ,
      },
      {/*21*/
        name: 'Curl de biceps polea',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/biceps/Curl de biceps en polea.gif', 
        photo: 'assets/imagenes/biceps/Curl de biceps en polea.jpg' ,
      },
      {/*22*/
        name: 'Curl de biceps en polea',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/biceps/Curl de biceps en polea.gif', 
        photo: 'assets/imagenes/biceps/Curl de biceps en polea.jpg' ,
      },
      { /*23*/
        name: 'Curl de biceps con barra',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/biceps/curl de biceps con barra.gif', 
        photo: 'assets/imagenes/biceps/curl de biceps con barra.jpg' ,
      },
      { /*24*/
        name: 'Curl de banco Scott',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/biceps/Curl en banco Scott.gif', 
        photo: 'assets/imagenes/biceps/Curl en banco Scott.jpg' ,
      },
      {/*25*/
        name: 'Curl de biceps agarre pronacion',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/biceps/Curl de biceps agarre pronacion.gif', 
        photo: 'assets/imagenes/biceps/Curl de biceps agarre pronacion.jpg' ,
      },
      {/*26*/
        name: 'Curl de biceps en polea alta',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/biceps/Curl de biceps en polea alta.gif', 
        photo: 'assets/imagenes/biceps/Curl de biceps en polea alta.jpg' ,
      },
      {/*27*/
        name: 'Curl de biceps en banco inclinados',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/biceps/Curl de biceps en banco inclinado.gif', 
        photo: 'assets/imagenes/biceps/Curl de biceps en banco inclinado.png' ,      },
      {/*28*///////////////////////////////////////////////////////////////////////////////////////////////////
        name: 'Dominadas agarre hancho pronacion',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/flexion delfin.gif', 
        photo: 'assets/imagenes/pectorales/fondos.jpg' ,
      },
      {/*29*/
        name: 'Dominada agarre supinacion',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/flexion delfin.gif', 
        photo: 'assets/imagenes/pectorales/fondos.jpg' ,
      },
      {/*30*/
        name: 'Dominada agarre pronacion',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/flexion delfin.gif', 
        photo: 'assets/imagenes/pectorales/fondos.jpg' ,
      },
      {/*31*/
        name: 'Dominada comando',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/flexion delfin.gif', 
        photo: 'assets/imagenes/pectorales/fondos.jpg' ,
      },
      {/*32*/
        name: 'Remos supinos',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/flexion delfin.gif', 
        photo: 'assets/imagenes/pectorales/fondos.jpg' ,
      },
      {/*33*/
        name: 'Dominada lateral',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/flexion delfin.gif', 
        photo: 'assets/imagenes/pectorales/fondos.jpg' ,
      },
      {/*34*/
        name: 'Curl de biceps agarre pronacion',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/flexion delfin.gif', 
        photo: 'assets/imagenes/pectorales/fondos.jpg' ,
      },
      {/*35*/
        name: 'Dominada en L',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/flexion delfin.gif', 
        photo: 'assets/imagenes/pectorales/fondos.jpg' ,
      },
      {/*36*/
        name: 'Dominada agarre mixto',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/flexion delfin.gif', 
        photo: 'assets/imagenes/pectorales/fondos.jpg' ,
      },/*///////////////////////////////////////////////////////////////////////////////////////////////////////*/
      {/*37*/
        name: 'Extencion de triceps en polea',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/triceps/Extencion de triceps en polea.gif', 
        photo: 'assets/imagenes/triceps/Extencion de triceps en polea.jpg' ,
      },
      {/*38*/
        name: 'Extension de triceps agarre invertido',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/triceps/Extension de triceps agarre invertido.gif', 
        photo: 'assets/imagenes/triceps/Extension de triceps agarre invertido.jpg' ,
      },
      {/*39*/
        name: 'Press frances con barra',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/triceps/Press frances con barra.gif', 
        photo: 'assets/imagenes/triceps/Press frances con barra.jpg' ,
      },
      {/*40*/
        name: 'Press frances con mancuernas',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/triceps/Press frances con mancuernas .gif', 
        photo: 'assets/imagenes/triceps/Press frances con mancuernas .jpeg' ,
      },
      {/*41*/
        name: 'Press frances parado',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/triceps/Press frances parado.gif', 
        photo: 'assets/imagenes/triceps/Press frances parado.png' ,
      },
      {/*42*/
        name: 'Extensiones de Tríceps con Polea alta',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/triceps/Extensiones de Tríceps con Polea alta.gif', 
        photo: 'assets/imagenes/triceps/Extensiones de Tríceps con Polea alta.jpeg' ,
      },
      {/*43*/
        name: 'Prensa en Banco para Tríceps',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/triceps/Prensa en Banco para Tríceps.gif', 
        photo: 'assets/imagenes/triceps/Prensa en Banco para Tríceps.jpeg' ,
      },
      {/*44*/
        name: 'Extension de triceps inclinado con mancuerna',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/triceps/Extension de triceps inclinado con mancuerna.gif', 
        photo: 'assets/imagenes/triceps/Extension de triceps inclinado con mancuerna.jpeg' ,
      },
      {/*45*/
        name: 'Extension de triceps en polea a una mano',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/triceps/Extension de triceps en polea a una mano.gif', 
        photo: 'assets/imagenes/triceps/Extension de triceps en polea a una mano.jpeg' ,
      },
      {/*46*/
        name: 'Flexiones Diamantes',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/flexion delfin.gif', 
        photo: 'assets/imagenes/pectorales/fondos.jpg' ,
      },
      {/*47*/
        name: 'Fondos en paralelas',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/flexion delfin.gif', 
        photo: 'assets/imagenes/pectorales/fondos.jpg' ,
      },
      {/*48*/
        name: 'Fondos en banco',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/flexion delfin.gif', 
        photo: 'assets/imagenes/pectorales/fondos.jpg' ,
      },
      {/*49*/
        name: 'Fondos en barra recta',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/flexion delfin.gif', 
        photo: 'assets/imagenes/pectorales/fondos.jpg' ,
      },
      {/*50*/
        name: 'Fondos Coreanos',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/flexion delfin.gif', 
        photo: 'assets/imagenes/pectorales/fondos.jpg' ,
      },
      {/*51*/
        name: 'Flexiones en Vertical',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/flexion delfin.gif', 
        photo: 'assets/imagenes/pectorales/fondos.jpg' ,
      },
      {/*52*/
        name: 'Extensión de Tríceps en Suelo',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/flexion delfin.gif', 
        photo: 'assets/imagenes/pectorales/fondos.jpg' ,
      },
      {/*53*/
        name: 'Extensión de Tríceps en Barra',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/flexion delfin.gif', 
        photo: 'assets/imagenes/pectorales/fondos.jpg' ,
      },
      {/*54*/
        name: 'Fondos Imposibles',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/flexion delfin.gif', 
        photo: 'assets/imagenes/pectorales/fondos.jpg' ,
      },/*//////////////////////////////  EJERCICIOS DE ABDOMEN   //////////////////////////////////////////////////////*/
      {/*55*/
        name: 'Polea al pecho',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/flexion delfin.gif', 
        photo: 'assets/imagenes/pectorales/fondos.jpg' ,
      },
      {/*56*/
        name: 'Polea al pecho con agarre estrecho',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/flexion delfin.gif', 
        photo: 'assets/imagenes/pectorales/fondos.jpg' ,
      },
      {/*57*/
        name: 'Pull over polea alta',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/flexion delfin.gif', 
        photo: 'assets/imagenes/pectorales/fondos.jpg' ,
      },
      {/*58*/
        name: 'Remo en polea baja',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/flexion delfin.gif', 
        photo: 'assets/imagenes/pectorales/fondos.jpg' ,
      },
      {/*59*/
        name: 'Remo con mancuerna',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/flexion delfin.gif', 
        photo: 'assets/imagenes/pectorales/fondos.jpg' ,
      },
      {/*60*/
        name: 'Remo con barra prono ',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/flexion delfin.gif', 
        photo: 'assets/imagenes/pectorales/fondos.jpg' ,
      },
      {/*61*/
        name: 'Polea al pecho agarre supino',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/flexion delfin.gif', 
        photo: 'assets/imagenes/pectorales/fondos.jpg' ,
      },
      {/*62*/
        name: 'Remo con barra supino',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/flexion delfin.gif', 
        photo: 'assets/imagenes/pectorales/fondos.jpg' ,
      },
      {/*63*/
        name: 'Remo con mancuernas inclinado',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/flexion delfin.gif', 
        photo: 'assets/imagenes/pectorales/fondos.jpg' ,
      },
      {/*64*/
        name: 'Remo con mancuernas inclinado',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/flexion delfin.gif', 
        photo: 'assets/imagenes/pectorales/fondos.jpg' ,
      },/*/////////////////////////////////////     ESPALDA PESO CORPORAL  ////////////////////// ////////////////////*/
      {/*65*/
        name: 'Dominadas agarre hancho pronacion',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/flexion delfin.gif', 
        photo: 'assets/imagenes/pectorales/fondos.jpg' ,
      },{/*66*/
         name: 'Dominada agarre supinacion',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/flexion delfin.gif', 
        photo: 'assets/imagenes/pectorales/fondos.jpg' ,
      },
      {/*67*/
        name: 'Dominadas agarre pronacion',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/flexion delfin.gif', 
        photo: 'assets/imagenes/pectorales/fondos.jpg' ,
      },{/*68*/
        name: 'Dominada comando',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/flexion delfin.gif', 
        photo: 'assets/imagenes/pectorales/fondos.jpg' ,
      },{/*69*/
        name: 'Remos supinos ',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/flexion delfin.gif', 
        photo: 'assets/imagenes/pectorales/fondos.jpg' ,
      },{/*70*/
        name: 'Dominada latera;',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/flexion delfin.gif', 
        photo: 'assets/imagenes/pectorales/fondos.jpg' ,
      },{/*71*/
        name: 'Curl de biceps agarre pronacion',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/flexion delfin.gif', 
        photo: 'assets/imagenes/pectorales/fondos.jpg' ,
      },{/*72*/
        name: 'Dominada en L',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/flexion delfin.gif', 
        photo: 'assets/imagenes/pectorales/fondos.jpg' ,
      },
      {/*73*/
        name: 'Dominada agarre mixto',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/flexion delfin.gif', 
        photo: 'assets/imagenes/pectorales/fondos.jpg' ,
      },/*//////////////////////////////////////           ABDOMEN CON MAQUINA  ///////////////////////////////////////*/
      {/*74*/
        name: 'Curl de abdomen',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/abdomen/curlabdomen.gif', 
        photo: 'assets/imagenes/abdomen/curl de abdomen.jpg' ,
      },
      {/*75*/
        name: 'Curl de abdomen declinado',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/abdomen/curlabdomendeclinado.gif', 
        photo: 'assets/imagenes/abdomen/curl de abdomen.jpg' ,
      },
      {/*76*/
        name: 'Flexión de piernas en banca',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/abdomen/Flexión de piernas en banca.gif', 
        photo: 'assets/imagenes/abdomen/Flexión de piernas en banca.jpg' ,
      },
      {/*77*/
        name: 'Curl en polea',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/abdomen/encogimientos abdominales en polea.gif', 
        photo: 'assets/imagenes/abdomen/curl en polea.jpg' ,
      },
      {/*78*/
        name: 'Laterales con mancuernas ',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/abdomen/Laterales con mancuernas .gif', 
        photo: 'assets/imagenes/abdomen/Laterales con mancuernas.jpg' ,
      },
      {/*79*/
        name: 'Rotaciones laterales',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/abdomen/rotaciones laterales.gif', 
        photo: 'assets/imagenes/abdomen/rotaciones laterales.jpg' ,
      },
      {/*80*/
        name: 'Elevaciones de rodillas en paralelas',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/abdomen/Elevaciones de rodillas en paralelas.gif', 
        photo: 'assets/imagenes/abdomen/Elevaciones de rodillas en paralelas.jpg' ,
      },
      {/*81*/
        name: 'Plancha en movimiento',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/abdomen/Plancha en movimiento.gif', 
        photo: 'assets/imagenes/abdomen/plancha en movimiento.jpeg' ,
      },
      {/*82*/
        name: 'Elevaciones de Tronco Banco Inclinado',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/abdomen/Elevaciones de Tronco Banco Inclinado.gif', 
        photo: 'assets/imagenes/abdomen/Elevaciones de Tronco Banco Inclinado.jpeg' ,
      },{/*83*/
        /*//////////////////////////////       EJERCICIOS DE GLUTEOS ////////////////////   ///////////////////////  */
        name: 'Cuadriceps - Extensiones de Piernas',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/gluteos/Cuadriceps - Extensiones de Piernas.gif', 
        photo: 'assets/imagenes/gluteos/Cuadriceps - Extensiones de Piernas.jpg' ,
      },{/*84*/
        name: 'Curl de Piernas Acostado',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/gluteos/Curl de Piernas Acostado.gif', 
        photo: 'assets/imagenes/gluteos/Curl de Piernas Acostado.jpeg' ,
      },{/*85*/
        name: 'Elevación de Talones con Barra en Pared',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/gluteos/Elevación de Talones con Barra en Pared.gif', 
        photo: 'assets/imagenes/gluteos/Elevación de Talones con Barra en Pared.jpeg' ,
      },{/*86*/
        name: 'El Peso Muerto con Piernas Extendidas',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/gluteos/El Peso Muerto con Piernas Extendidas.gif', 
        photo: 'assets/imagenes/gluteos/El Peso Muerto con Piernas Extendidas.jpeg' ,
      },{/*87*/
        name: 'Flexion con mancuernas',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/gluteos/Flexion con mancuernas.gif', 
        photo: 'assets/imagenes/gluteos/Flexion con mancuernas.jpg' ,
      },{/*88*/
        name: 'prensa de piernas',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/gluteos/prensa de piernas.gif', 
        photo: 'assets/imagenes/gluteos/prensa de piernas.jpg' ,
      },{/*89*/
        name: 'sancadas con barra',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/gluteos/sancadas con barra.gif', 
        photo: 'assets/imagenes/gluteos/sancadas con barra.jpg' ,
      },
      {/*90*/
        name: 'sentadillas con barra',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/gluteos/sentadillas con barra.gif', 
        photo: 'assets/imagenes/gluteos/sentadillas con barra.png' ,
      },
      {/*91*/
        name: 'Pantorrilas - Elevaciones de Talones Sentado',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/gluteos/Pantorrilas - Elevaciones de Talones Sentado.gif', 
        photo: 'assets/imagenes/gluteos/Pantorrilas - Elevaciones de Talones Sentado.jpeg' ,
      },/*/////////////////////////////////////////// EJERCICIOS DE ANTEBRAZOS /////////////////////*/
      {/*92*/
        name: 'Curl Banco Scott Invertido',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/antebrazo/Curl Banco Scott Invertido.gif', 
        photo: 'assets/imagenes/antebrazo/Curl de Muñeca Invertido.jpg' ,
      },
      {/*93*/
        name: 'Curl Barra Invertido',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/antebrazo/Curl Barra Invertido.gif', 
        photo: 'assets/imagenes/antebrazo/Curl Barra Invertido.jpg' ,
      },
      {/*94*/
        name: 'Curl de Muñeca',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/antebrazo/curl de muneca.gif', 
        photo: 'assets/imagenes/antebrazo/Curl de Muñeca.jpg' ,
      },
      {/*95*/
        name: 'Curl de Muñeca Atrás de la Espalda',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/antebrazo/Curl de Muñeca Atrás de la Espalda.gif', 
        photo: 'assets/imagenes/antebrazo/Curl de Muñeca Atrás de la Espaldaa.gif' ,
      },
      {/*96*/
        name: 'Curl de Muñeca Invertido',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/antebrazo/Curl de Muñeca Invertido.gif', 
        photo: 'assets/imagenes/antebrazo/Curl de Muñeca Invertido.jpg' ,
      },/*////////////////////////////// EJERCICIOS DE HOMBRO Y TRaPECIO//////////////////////////////////*/
      {/*97*/
        name: 'apertura inversas mancuernas',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/hombros/apertura inversas mancuernas.jpg', 
        photo: 'assets/imagenes/hombros/apertura inversas mancuernas.jpeg' ,
      },
      {/*98*/
        name: 'Elevaciones Frontales con Disco',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/hombros/Elevaciones Frontales con Disco.gif', 
        photo: 'assets/imagenes/hombros/Elevaciones Frontales con Disco.jpeg' ,
      },
      {/*99*/
        name: 'Elevación Frontal con Mancuerna',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/hombros/Elevación Frontal con Mancuerna.gif', 
        photo: 'assets/imagenes/hombros/Elevación Frontal con Mancuerna.png ' ,
      },
      {/*100*/
        name: 'extension hombros en polea',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/hombros/extension hombros en polea.gif', 
        photo: 'assets/imagenes/hombros/extension hombros en polea.jpg' ,
      },
      {/*101*/
        name: 'Levantamientos Laterales con Mancuernas',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho',
        image: 'assets/imagenes/hombros/Levantamientos Laterales con Mancuernas.gif', 
        photo: 'assets/imagenes/hombros/Levantamientos Laterales con Mancuernas.png' ,
      },
      {/*102*/
        name: 'Press Militar',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/hombros/Press Militar.gif', 
        photo: 'assets/imagenes/hombros/Press Militar.jpg' ,
      },
      {/*103*/
        name: 'Press Militar Sentado',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/hombros/Press Militar Sentado.gif', 
        photo: 'assets/imagenes/hombros/Press Militar Sentado.jpeg' ,
      },
      {/*104*/
        name: 'Remo al mentón con agarre ancho',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/hombros/Remo al mentón con agarre ancho.gif', 
        photo: 'assets/imagenes/hombros/Remo al mentón con agarre ancho.jpeg' ,
      },/*//////////////////////////////////////////////////////////////////////////////////////////////*/
      {/*89*/
        name: 'Dominadas Polea Nuca',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/flexion delfin.gif', 
        photo: 'assets/imagenes/pectorales/fondos.jpg' ,
      },
      {/*89*/
        name: 'Dominadas Polea Nuca',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/flexion delfin.gif', 
        photo: 'assets/imagenes/pectorales/fondos.jpg' ,
      },
      {/*89*/
        name: 'Dominadas Polea Nuca',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/flexion delfin.gif', 
        photo: 'assets/imagenes/pectorales/fondos.jpg' ,
      },/*90*/
      {/*89*/
        name: 'Dominadas Polea Nuca',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/flexion delfin.gif', 
        photo: 'assets/imagenes/pectorales/fondos.jpg' ,
      },/*90*/
      {/*89*/
        name: 'Dominadas Polea Nuca',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/flexion delfin.gif', 
        photo: 'assets/imagenes/pectorales/fondos.jpg' ,
      },/*90*/
      {/*89*/
        name: 'Dominadas Polea Nuca',
        quote1: '1.Acostarse en un banco pano' ,
        quote2: '2.Tomar barra en agarre pronacion' ,
        quote3: '3.Inhalar mientras bajas la barra al pecho' ,
        quote4: '4.Exhalar mientras subes la barra del pecho' ,
        image: 'assets/imagenes/pectorales/flexion delfin.gif', 
        photo: 'assets/imagenes/pectorales/fondos.jpg' ,
      },/*90*/
      


      ];
      this.character = characters[this.params.get('charNum')];
  }

  ionViewDidLoad() {
    console.log('ionViewDidLoad InformacionPage');
  }

  

}
